# Generated by Django 4.1.3 on 2022-11-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_member_add', '0002_teammember_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='phoneNumber',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('Regular', "Regular - Can't delete members"), ('Admin', 'Admin - Can delete members')], default='Regular', max_length=50),
        ),
    ]
