# Generated by Django 4.1.3 on 2022-11-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_member_add', '0004_alter_teammember_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='phoneNumber',
            field=models.PositiveBigIntegerField(),
        ),
    ]
